### ISSUE TITLE
Rios ACLs & consent types are not updating for all biospecimens

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-lambda-update-dbgap-consent#20]
We released a new study the other week - Rios. The ACLs are not updating and the consent types are not updating for all specimens - there is a large % that did not update. 

@dankolbman Looked at it some and said there is a bug. Can you work with him, @parimalak ?

We need to get these assigned.

**Comment by parimalak** [comment]
@baileyckelly updated acl's in production manually. I will look deeper into code and fix.

**Comment by baileyckelly** [comment]
@parimalak There's still an issue.

This is what is in the database:

![Screen Shot 2018-11-06 at 7.30.32 AM.png](https://images.zenhubusercontent.com/5a29f7738a75884b908a582d/0ff1060d-c1ab-4c63-9730-3ba5e206908e)

This is what is on dbgap: https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/GetSampleStatus.cgi?study_id=phs001410&rettype=html

There should be no HMB-IRB. The ACL tool looks like it updated some of them to plain HMB. But it didnt update the 72 - the same 72 that we originally reported. Why not?

select b.consent_type, b.dbgap_consent_code, count(b.*), count(p.*)
from participant p
left join biospecimen b
on p.kf_id = b.participant_id
where p.study_id = 'SD_RM8AFW0R'
group by b.consent_type, b.dbgap_consent_code

If this isnt something we can sort out quickly, we may need to manually update the values with code.

**Comment by baileyckelly** [comment]
SQL so I dont lose it:

select b.consent_type, b.dbgap_consent_code, count(b.*), count(p.*)
from participant p
left join biospecimen b
on p.kf_id = b.participant_id
where p.study_id = 'SD_RM8AFW0R'
group by b.consent_type, b.dbgap_consent_code
